//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4216
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeklaProperties.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TeklaProperties.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap STEEP_FLANKED_BEVEL_GROOVE_SINGLE_BEVEL_BUTT {
            get {
                object obj = ResourceManager.GetObject("STEEP_FLANKED_BEVEL_GROOVE_SINGLE_BEVEL_BUTT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap STEEP_FLANKED_BEVEL_GROOVE_SINGLE_V_BUTT {
            get {
                object obj = ResourceManager.GetObject("STEEP_FLANKED_BEVEL_GROOVE_SINGLE_V_BUTT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WELD_TYPE_BEVEL_BACKING {
            get {
                object obj = ResourceManager.GetObject("WELD_TYPE_BEVEL_BACKING", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WELD_TYPE_BEVEL_GROOVE_SINGLE_BEVEL_BUTT {
            get {
                object obj = ResourceManager.GetObject("WELD_TYPE_BEVEL_GROOVE_SINGLE_BEVEL_BUTT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WELD_TYPE_BEVEL_GROOVE_SINGLE_V_BUTT {
            get {
                object obj = ResourceManager.GetObject("WELD_TYPE_BEVEL_GROOVE_SINGLE_V_BUTT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WELD_TYPE_CORNER_FLANGE {
            get {
                object obj = ResourceManager.GetObject("WELD_TYPE_CORNER_FLANGE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WELD_TYPE_EDGE {
            get {
                object obj = ResourceManager.GetObject("WELD_TYPE_EDGE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WELD_TYPE_EDGE_FLANGE {
            get {
                object obj = ResourceManager.GetObject("WELD_TYPE_EDGE_FLANGE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WELD_TYPE_FILLET {
            get {
                object obj = ResourceManager.GetObject("WELD_TYPE_FILLET", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WELD_TYPE_FLARE_BEVEL_GROOVE {
            get {
                object obj = ResourceManager.GetObject("WELD_TYPE_FLARE_BEVEL_GROOVE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WELD_TYPE_FLARE_V_GROOVE {
            get {
                object obj = ResourceManager.GetObject("WELD_TYPE_FLARE_V_GROOVE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WELD_TYPE_FOLD {
            get {
                object obj = ResourceManager.GetObject("WELD_TYPE_FOLD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WELD_TYPE_INCLINED {
            get {
                object obj = ResourceManager.GetObject("WELD_TYPE_INCLINED", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WELD_TYPE_ISO_SURFACING {
            get {
                object obj = ResourceManager.GetObject("WELD_TYPE_ISO_SURFACING", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WELD_TYPE_J_GROOVE_J_BUTT {
            get {
                object obj = ResourceManager.GetObject("WELD_TYPE_J_GROOVE_J_BUTT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WELD_TYPE_MELT_THROUGH {
            get {
                object obj = ResourceManager.GetObject("WELD_TYPE_MELT_THROUGH", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WELD_TYPE_NONE {
            get {
                object obj = ResourceManager.GetObject("WELD_TYPE_NONE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WELD_TYPE_NONE1 {
            get {
                object obj = ResourceManager.GetObject("WELD_TYPE_NONE1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WELD_TYPE_PARTIAL_PENETRATION_SINGLE_BEVEL_BUTT_PLUS_FILLET {
            get {
                object obj = ResourceManager.GetObject("WELD_TYPE_PARTIAL_PENETRATION_SINGLE_BEVEL_BUTT_PLUS_FILLET", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WELD_TYPE_PARTIAL_PENETRATION_SQUARE_GROOVE_PLUS_FILLET {
            get {
                object obj = ResourceManager.GetObject("WELD_TYPE_PARTIAL_PENETRATION_SQUARE_GROOVE_PLUS_FILLET", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WELD_TYPE_PLUG {
            get {
                object obj = ResourceManager.GetObject("WELD_TYPE_PLUG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WELD_TYPE_SEAM {
            get {
                object obj = ResourceManager.GetObject("WELD_TYPE_SEAM", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WELD_TYPE_SINGLE_BEVEL_BUTT_WITH_BROAD_ROOT_FACE {
            get {
                object obj = ResourceManager.GetObject("WELD_TYPE_SINGLE_BEVEL_BUTT_WITH_BROAD_ROOT_FACE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WELD_TYPE_SINGLE_V_BUTT_WITH_BROAD_ROOT_FACE {
            get {
                object obj = ResourceManager.GetObject("WELD_TYPE_SINGLE_V_BUTT_WITH_BROAD_ROOT_FACE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WELD_TYPE_SLOT {
            get {
                object obj = ResourceManager.GetObject("WELD_TYPE_SLOT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WELD_TYPE_SPOT {
            get {
                object obj = ResourceManager.GetObject("WELD_TYPE_SPOT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WELD_TYPE_SQUARE_GROOVE_SQUARE_BUTT {
            get {
                object obj = ResourceManager.GetObject("WELD_TYPE_SQUARE_GROOVE_SQUARE_BUTT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WELD_TYPE_U_GROOVE_SINGLE_U_BUTT {
            get {
                object obj = ResourceManager.GetObject("WELD_TYPE_U_GROOVE_SINGLE_U_BUTT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
